/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef IOSREVIEW_AUTODEFS_H
#define IOSREVIEW_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_IOSREVIEW_NAME "IOSReview"
#define S3E_EXT_IOSREVIEW_HASH 0xcf6dbfc2

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("IOSReview", 1)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !IOSREVIEW_AUTODEFS_H */
