/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*requestReview_t)();

/**
 * struct that gets filled in by IOSReviewRegister
 */
typedef struct IOSReviewFuncs
{
    requestReview_t m_requestReview;
} IOSReviewFuncs;
